on:
  pull_request:
  push:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/build-push-action@v6

  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: psf/black@stable
        with:
          options: "--check --verbose"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: |
          python -m pip install --upgrade pip
          pip install pylint

      - run: |
          pylint $(git ls-files '*.py')
